### ISSUE TITLE
some ideas

### ISSUE THREAD

**Issue by thearnavrustagi** [shansitads/Predicitve-Search#1]
okay idk I know some java so somethings you need to do:-
1)use quick sort algorithm by either implementing it or use Arrays.parrallelSort(arg);
2)use a little oop
3)make code a lil more readable by puting main in the top
4)use generics to make the code more efficient,it is syntactic sugar but it works

**Comment by argonsodiumvanadium** [comment]
oh and the inerpolation search implementation is nice, and use a file reader to read from a file and then split it with String.split(Delim)

**Comment by shansitads** [comment]
Ok sure I'll add that soon. Thanks!

**Comment by thearnavrustagi** [comment]
okay so when I first saw your algorithm I was like wow! how did you do it so fast and small but when I did some test I realised it would not work so I forked your repository and made some tests in it and as you can see on the output your algorithm will fail to find numbers such as 4 and 9 in big array sizes such as 10 and it usually failed, so I can say with some confidence that on bigger lengths of the array the failure would be greater almost catastrophic(It gets caught in an infinite loop) and plus it does too many iterations it should ideally be 4 iterations for a regular iterations,<br>
just check the forked repo ad tell me if I messed up the implementation or something, and like fix the algorithm this comment is only there for help no malice is intended<br>
I removed Math.round as it gives a false sense that the array is being searched while it is not

**Comment by shansitads** [comment]
Ok when I had tried running it, it ran pretty well on larger values but I don't think I tried smaller values like 4 and 9. I'll check out the repo too.

**Comment by argonsodiumvanadium** [comment]
okay if you dont mind my curiosity how did you stumble on the formula because I mean i kinda get the gist of it now and you are right this is some kind of upgrade to the binary search and the error in your programs occurs when the high and low have a VERY big difference not that you need to know that but I take back my words your code is not interpolation because it makes no sense when you compare it to interpolation idealogy so you might be onto something beautiful
there but the biggest error in your code might be the fact that you assume that the code is somewhat an arithmatic progression not a geometric or unknown one again you already know that so yeah but the reason i am saying this is I might have misinformed you earlier I knida regret it now

**Comment by shansitads** [comment]
Wait, did you comment something about interpolation an hour ago? I can't find the comment anymore so I don't know what exactly you had written.

**Comment by thearnavrustagi** [comment]
yes I commented but i deleted it
okay well I think I found the bug in the code and I dont want to share it with you for 3 reasons 
1)it will spoil the fun of discovering somethig on your own 
2)you will do a better job than me without a doubt
3)you are not implementing interpol search,now that I got the gist of your code you are right it is somekind of half mutated beautiful binary search algorithm but you have made one small bug which honestly i have no idea of how to solve, the solution i have is based on interpol search and violates your predictive search<br>
what I am saying is that I might have misinformed you on the fact that your algorithm was an interpol  search because it is not(as I have said(I might still be misinforming you because I dont like know the defination of interpol search but i know the gist of it and your algorithm does not follow it)) <br>
actually I am writing the bug down if you wanna see it it is fine though you might know it the real problem is how to solve it without implementing interpol search but your binary search 2.0<br>
#### BUG
### dont read this without reading the warning up there
you are assuming that all the numbers will have a some what uniform distribution, that is you are assuming that the numbers are in arithmatic series not in any variable series like geometric and some weird trignometric one

**Comment by shansitads** [comment]
Ah okay I see, yes I did assume that while making the program but afterwards I also realised that although it is not as effective in a geometrically series as it is with arithmetic series, it still works faster than/as fast as binary search. Additionally, the programme is for a general random dataset so it is not very likely for the data to be in a fixed mathematical series, which I why I just followed a general system. Thanks for the recommendations though!

**Comment by argonsodiumvanadium** [comment]
well idk I mean no matter how lousy my programs are i always try to prevent worst case scenarios (though I fail 90% of the time) but in general if your code can implement any variable function just like an interpol does then it would be truly beautiful and in a general data set I can give a very hypothetical example that it is possible in the future you use this faulty code to do some research on gravity and as [accelration = f(d)= 4.9d^2] then your algorithm will fail and plus it will not be a general purpose algorithm it would be preferable if you solve the issue though I honestly have no idea to do it, <br>if you wanna derive an interpol way which will work then after sorting the array assum that the value in a given index(i) is equivalent to a mysterious function f(i) that is value = f(i) and index is i <br> i derived my algorithm based on the above assumption, now your algorithm also has a interpol way though i did not check it as i knew i would get carried away and delay my own project and spoil your fun but there must be some interpol way<br>

**Comment by argonsodiumvanadium** [comment]
okay i found some kind of solution to your bug well it is not a solution it is more like prevention
```
int[] array = //initialized
int upperIndex = array.length-1,lowerIndex = 0; //initialize these
int max,min;

final float SAFE_VALUE = 0.75f;

lowerSlope = array[lowerIndex] - array[lowerIndex+1];
upperSlope = array[upperIndex-1] - array[upperIndex];
slope = ( array[upperIndex]-array[lowerIndex] )/array.length;

boolean bool = Math.abs(slope - lowerSlope) < SAFE_VALUE;
boolean alsoABool = Math.abs(slope - upperSlope) < SAFE_VALUE;

if(bool && alsoABool) {
//predictive search will run without an error 
return /* int location/value or nothing if void but put return statement */;
}
//print some kind of error or default to binary search or interpol search
return;
```

so this code will basically check if your predictive search will work or not if it is possible that your code WILL work then the if block will execute your code if it will not work then the if block will be ignored and the thread would go to the print error comment and you can default to whatever  you want, this will just prevent faults in your code as it will handle the worst case scenario of getting values which have a polynomial degree<br>

#### Note :- i have not checked this algorithm it is purely theoretical it should do the job but i can not guarantee it

**Comment by thearnavrustagi** [comment]
okay I mean I honestly dont care if anyone takes my recommendations (no seriously) but my main concern here is the fact that " YOUR CODE DOES NOT WORK ON A GEOMETRIC SERIES  ARRAY " if you have seen my test so like please dont write false knowledge and rectify the error I mean I know I should be the last one to say this as I make super buggy code but dont spread wrong facts,as your code is not only slower then binary search but also gets lost in an infinite loop when geometric values are given it is not a searching algorithm that is as one might say "perfect" if per say someone(like me) who gets impressed and tries the algorithm without testing it his code  will be doomed and he will be lost like what the hell happened, so either rectify the algorithm somehow or remove the statement that your code works on a geometric series

**Comment by shansitads** [comment]
I had tested the code by randomly generating 30 different arrays online and applying them on both searching methods. I had not tested the conditions manually so thanks for letting me know that there was an issue in the code. I'll definitely try to figure out a way to search geometric progressions after boards are over, but until then, I'll just add a warning in the description or temporarily take down the program.

**Comment by argonsodiumvanadium** [comment]
ok I kinda appologize for like acting weird and what not idk I mean usually I am a full nonsense guy but when I am serious I am like a no bullshit guy and like I want to achieve the best performance so idk I am just sorry for acting like weird, now obviously you dont work for me or some shit but the only reason i am pushing without any reason is because I find the concept beautiful in a different way and I am not gonna mention the other reasons so yaaahhh sorry

**Comment by argonsodiumvanadium** [comment]
okay, ummm, I was wondering if like after the boards if you are up for collaboration for building some packages I mean I was either ways going to make some packages to consolidate my knowledge after each project and like learn the elementary computer algorithms but like if you are up for it then that is like fine, because one of the classes I feel the need to  fix is the ArrayList and you could implement your search algorithm in it I mean it is buggy rn but I know a prevention method so that the code will default to bin search if the array is geometrically progressing, now another reason is the fact that together we can create a much richer package, now I will just add a word of warning that I WILL try other languages because I have found some very irritating faults in java, they are not major but I feel they are unnecessary irritations so yah I will probably try kotlin, go, scala ,c++ and some more so the library wont be pure java except the algorithms(These will be pure java or atleast mostly) and data structures(I can guarantee I will implement the new Dynamic array in java but I cant guarantee other data structures)

**Comment by argonsodiumvanadium** [comment]
okay, ummm, @shansitads I was wondering if like after the boards if you are up for collaboration for building some packages I mean I was either ways going to make some packages to consolidate my knowledge after each project and like learn the elementary computer algorithms but like if you are up for it then that is like fine, because one of the classes I feel the need to  fix is the ArrayList and you could implement your search algorithm in it I mean it is buggy rn but I know a prevention method so that the code will default to bin search if the array is geometrically progressing, now another reason is the fact that together we can create a much richer package,<br>
I will just add a word of warning that I WILL try other languages because I have found some very irritating faults in java, they are not major but I feel they are unnecessary and irritating so yah I will probably try kotlin, go, scala ,c++ and some more languages so the library wont be pure java except the algorithms(These will be pure java or atleast mostly) and data structures(I can guarantee I will implement the new Dynamic array in java but I cant guarantee other data structures)
